/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AccountHandler;

import java.awt.Dimension;
import java.awt.Toolkit;
import com.twilio.Twilio;
import com.twilio.rest.api.v2010.account.Message;
import com.twilio.type.PhoneNumber;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author User
 */
public class ForgetPasswordForm extends javax.swing.JFrame {

    
    private final int AuthCode; //Variable Storing The Verification Code
    /**
     * Creates new form ForgetPasswordForm
     */
    public ForgetPasswordForm() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
int x = (screenSize.width - getWidth()) / 2;
int y = (screenSize.height - getHeight()) / 2;
setLocation(x, y);
AuthCode=generateRandomCode();
NewPasswordField.setEditable(false);
PhoneNumberTextField.setEditable(false);
JOptionPane.showMessageDialog(null, "Please Write Your Country Code When Entering Your Number As The Verification Code Cannot Be Sent Without It!", "Forget Password", JOptionPane.WARNING_MESSAGE);
setTitle("Clothing Shop Management System - Forget Password");
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PhoneNumberTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        VerificationCodeTextField = new javax.swing.JTextField();
        SendVerificationCodeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        SetNewPasswordButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        VerifyButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        FindUserButon = new javax.swing.JButton();
        ShowPasswordCheckBox = new javax.swing.JCheckBox();
        NewPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forgot Password?");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone Number");

        PhoneNumberTextField.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        PhoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Verification Code");

        VerificationCodeTextField.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N

        SendVerificationCodeButton.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        SendVerificationCodeButton.setText("Send Verification Code");
        SendVerificationCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendVerificationCodeButtonActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password");

        SetNewPasswordButton.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        SetNewPasswordButton.setText("Set");
        SetNewPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetNewPasswordButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        VerifyButton.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        VerifyButton.setText("Verify");
        VerifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyButtonActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");

        UsernameTextField.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N

        FindUserButon.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        FindUserButon.setText("Find User");
        FindUserButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindUserButonActionPerformed(evt);
            }
        });

        ShowPasswordCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        ShowPasswordCheckBox.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        ShowPasswordCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        ShowPasswordCheckBox.setText("Show Password");
        ShowPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordCheckBoxActionPerformed(evt);
            }
        });

        NewPasswordField.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SetNewPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ShowPasswordCheckBox)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(NewPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VerificationCodeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsernameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SendVerificationCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(VerifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addComponent(FindUserButon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindUserButon))
                .addGap(75, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(VerificationCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendVerificationCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ShowPasswordCheckBox)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetNewPasswordButton)
                    .addComponent(BackButton))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendVerificationCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendVerificationCodeButtonActionPerformed
       setUpTwilio();
    }//GEN-LAST:event_SendVerificationCodeButtonActionPerformed

    private void PhoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTextFieldActionPerformed

    private void VerifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyButtonActionPerformed
        if(VerifyingCode()==true)
        {
            NewPasswordField.setEditable(true);
            JOptionPane.showMessageDialog(null, "Verification Code Matched, Please Set Your New Password", "Forget Password", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Verification Code Did Not Match, Please Try Again", "Forget Password", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_VerifyButtonActionPerformed

    private void SetNewPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetNewPasswordButtonActionPerformed
        String NewPassword=NewPasswordField.getText();
        String Username=UsernameTextField.getText();
        String filepath="signup_info" + "_" + Username + ".txt";
        String line;
        boolean passwordChanged=false;
        try{
            File file=new File(filepath);
            File fileTemp=new File("temp.txt");
            BufferedReader reader=new BufferedReader(new FileReader(file));
            BufferedWriter writer=new BufferedWriter(new FileWriter(fileTemp));
            while((line=reader.readLine())!=null)
            {
                if(line.startsWith("Password: "))
                {
                    writer.write("Password: "+NewPassword);
                    writer.newLine();
                    passwordChanged=true;
                }
                else
                {
                    writer.write(line);
                    writer.newLine();
                    
                }
                    
            }
            writer.close();
            reader.close();
            
            if(passwordChanged)
            {
                file.delete();
                fileTemp.renameTo(file);
                JOptionPane.showMessageDialog(null, "Password Successfully Changed!", "Forget Password", JOptionPane.INFORMATION_MESSAGE);
                Login login=new Login();
                this.setVisible(false);
                login.setVisible(true);
            }
            else
            {
                fileTemp.delete();
                JOptionPane.showMessageDialog(null, "An Error Occurred", "Forget Password", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        catch(IOException IOE)
        {
            JOptionPane.showMessageDialog(null, IOE.getMessage(), "Forget Password", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_SetNewPasswordButtonActionPerformed

    private void FindUserButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindUserButonActionPerformed
        try{
        if(checkUserExists())
        {
            JOptionPane.showMessageDialog(null, "User Successfully Found!", "Forget Password", JOptionPane.INFORMATION_MESSAGE);
            PhoneNumberTextField.setEditable(true);
        }
       
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Forget Password", JOptionPane.ERROR_MESSAGE);
        }
        
       
        
    }//GEN-LAST:event_FindUserButonActionPerformed

    private void ShowPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordCheckBoxActionPerformed
        if(ShowPasswordCheckBox.isSelected())
        {
            NewPasswordField.setEchoChar((char)0);
        }
        else
        {
             NewPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPasswordCheckBoxActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        Login login=new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

     private int generateRandomCode()
    {
        Random rand=new Random();
        
        return rand.nextInt(90000)+10000;
    }
     
     private boolean checkUserExists() throws Exception
     {
         String Username=UsernameTextField.getText();
         String filepath="signup_info" + "_" + Username + ".txt";
         File file=new File(filepath);
         if(file.exists())
         {
             return true;
         }
         else
         {
             throw new Exception("User Not Found");
         }
     }
     
    
    
     private boolean VerifyingCode()
     {
         int Code=AuthCode;
         String CodeString=String.valueOf(Code).trim();
         String EnteredVerificationCode=VerificationCodeTextField.getText();
         
         if(EnteredVerificationCode.equals(CodeString))
         {
             return true;
         }
         return false;
     }
    
    private void setUpTwilio()
    {
       int VerificationCode=AuthCode;
       final String ACCOUNT_SID="AC4b3606b741e3fdcb47a764f4015d0ce9";
       final String AUTH_TOKEN="b930563e9e59a67d5cd087e73237cb1d";
       
       try{
       Twilio.init(ACCOUNT_SID,AUTH_TOKEN);
       
       Message message = Message.creator(
            new PhoneNumber(PhoneNumberTextField.getText()),   
            new PhoneNumber("+12487214957"),   
            "Your Verification Code is"+" "+VerificationCode
        ).create();
       JOptionPane.showMessageDialog(null, "Verification Code Sent Successfully", "Forget Password", JOptionPane.INFORMATION_MESSAGE);
       
       System.out.println(message.getSid());
       }
       
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
           
       }
       
       
    }
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton FindUserButon;
    private javax.swing.JPasswordField NewPasswordField;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JButton SendVerificationCodeButton;
    private javax.swing.JButton SetNewPasswordButton;
    private javax.swing.JCheckBox ShowPasswordCheckBox;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JTextField VerificationCodeTextField;
    private javax.swing.JButton VerifyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
